env:
    BUILD_USER: rosy
    BUILD_HOST: nha-project
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/ci
    
task:
  name: "Build deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env
  
  Disk_check_script:
      - ./disk.sh
      
  Sync_script:
      - ./sync
  
  Build_script:
      - ./build

